// Embeds the repository builds and the frozen route into a TS module so the
// server can register them without reading the file system at runtime.
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const html = fs.readFileSync(path.join(root, 'games/gravity-room/a/index.html'), 'utf8');
const route = JSON.parse(fs.readFileSync(path.join(root, 'games/gravity-room/route.json'), 'utf8'));
const sha = createHash('sha256').update(html, 'utf8').digest('hex');

const out = `// GENERATED by scripts/gen-builds.mjs. Do not edit by hand.
// Source: games/gravity-room/a/index.html (sha256 ${sha})
import type { RouteStep } from './headless.ts';

export const GRAVITY_ROOM_A_HTML: string = ${JSON.stringify(html)};
export const GRAVITY_ROOM_A_SHA256 = ${JSON.stringify(sha)};
export const GRAVITY_ROOM_ROUTE: { route: RouteStep[]; deathRoute: RouteStep[] } = ${JSON.stringify({ route: route.route, deathRoute: route.deathRoute })};
`;
fs.writeFileSync(path.join(root, 'lib/game/builds.generated.ts'), out);
console.log(`lib/game/builds.generated.ts written (A sha256 ${sha.slice(0, 12)}…)`);
