-- Provisioning of service identities (the backend worker) and rehearsal users.
--
-- The backend never needs the service-role key in production: it signs in as
-- a dedicated user whose app_metadata.funlabs_role = 'worker', and RLS grants
-- that identity exactly what the processing pipeline needs. Only SQL run by
-- the database owner can call this function; the password is generated by the
-- operator and stored only in the deployment's environment variables.

create or replace function private.provision_user(p_email text, p_password text, p_app_meta jsonb default '{}'::jsonb, p_display_name text default null)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
begin
  if p_password is null or char_length(p_password) < 24 then
    raise exception 'The service password must be at least 24 characters long' using errcode = '22023';
  end if;
  select id into v_id from auth.users where email = lower(p_email);
  if v_id is null then
    v_id := gen_random_uuid();
    insert into auth.users (
      instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
      raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
      confirmation_token, recovery_token, email_change_token_new, email_change
    ) values (
      '00000000-0000-0000-0000-000000000000', v_id, 'authenticated', 'authenticated', lower(p_email),
      extensions.crypt(p_password, extensions.gen_salt('bf')), now(),
      jsonb_build_object('provider', 'email', 'providers', jsonb_build_array('email')) || coalesce(p_app_meta, '{}'::jsonb),
      jsonb_build_object('display_name', coalesce(p_display_name, split_part(p_email, '@', 1))),
      now(), now(), '', '', '', ''
    );
    insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
    values (
      gen_random_uuid(), v_id, v_id::text,
      jsonb_build_object('sub', v_id::text, 'email', lower(p_email), 'email_verified', true),
      'email', now(), now(), now()
    );
  else
    update auth.users
       set encrypted_password = extensions.crypt(p_password, extensions.gen_salt('bf')),
           raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb) || coalesce(p_app_meta, '{}'::jsonb),
           email_confirmed_at = coalesce(email_confirmed_at, now()),
           updated_at = now()
     where id = v_id;
  end if;
  return v_id;
end;
$$;

revoke execute on function private.provision_user(text, text, jsonb, text) from public, anon, authenticated;
